# Generated by Django 3.1.2 on 2021-01-02 18:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastel',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
