# Generated by Django 3.1.2 on 2021-01-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastel',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
