# Generated by Django 3.1.2 on 2021-01-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastel', '0002_auto_20210101_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastel',
            name='foto',
            field=models.URLField(),
        ),
    ]
