# Generated by Django 3.1.2 on 2021-01-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastel', '0003_auto_20210101_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastel',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
